### ISSUE TITLE
How to resume the training?

### ISSUE THREAD

**Issue by sushil-bharati** [ARCC-RACE/deepracer-for-dummies#38]
how to resume the training?

I tried running `set-last-run-to-pretrained.sh` followed by `start.sh` but it still shows `"module_dir": "s3://bucket/rl-deepracer-sagemaker/source/sourcedir.tar.gz"` . Is that correct??

 How to make sure that I am resuming training in the terminal?

**Comment by Michael-Equi** [comment]
When sagemaker starts up does it say that it is loading a presaved checkpoint?

**Comment by sushil-bharati** [comment]
I am closing this issue because I believe sagemaker says that somewhere in console. Thanks.
