### ISSUE TITLE
Sagemarker Log Terminal Missing

### ISSUE THREAD

**Issue by arrickx** [ARCC-RACE/deepracer-for-dummies#51]
Here are the two terminal page showing.

![Screenshot from 2019-09-20 00-40-57](https://user-images.githubusercontent.com/24638167/65299898-6545b300-db3f-11e9-978d-7220d754ed52.png)
![Screenshot from 2019-09-20 00-41-19](https://user-images.githubusercontent.com/24638167/65299899-6545b300-db3f-11e9-9d87-d54649e75ed2.png)

Tried to reinstall ubuntu and try it one more time but still. Not sure how it goes.

**Comment by albertsundjaja** [comment]
I'm adding more sleep time in the `start.sh` script. It seems the container need more time to load. see how it goes with yours?

```
#sleep for 20 seconds to allow the containers to start
sleep 15
```

here change it into 30 or something
